![NYC Skyline](nyc.jpg)

Welcome to New York City, one of the most-visited cities in the world. There are many Airbnb listings in New York City to meet the high demand for temporary lodging for travelers, which can be anywhere between a few nights to many months. In this project, we will take a closer look at the New York Airbnb market by combining data from multiple file types like `.csv`, `.tsv`, and `.xlsx`.

Recall that **CSV**, **TSV**, and **Excel** files are three common formats for storing data. 
Three files containing data on 2019 Airbnb listings are available to you:

**data/airbnb_price.csv**
This is a CSV file containing data on Airbnb listing prices and locations.
- **`listing_id`**: unique identifier of listing
- **`price`**: nightly listing price in USD
- **`nbhood_full`**: name of borough and neighborhood where listing is located

**data/airbnb_room_type.xlsx**
This is an Excel file containing data on Airbnb listing descriptions and room types.
- **`listing_id`**: unique identifier of listing
- **`description`**: listing description
- **`room_type`**: Airbnb has three types of rooms: shared rooms, private rooms, and entire homes/apartments

**data/airbnb_last_review.tsv**
This is a TSV file containing data on Airbnb host names and review dates.
- **`listing_id`**: unique identifier of listing
- **`host_name`**: name of listing host
- **`last_review`**: date when the listing was last reviewed

In [9]:
# Import necessary packages
import pandas as pd
import numpy as np

# Look at the first few rows of the data

airbnb_price = pd.read_csv('data/airbnb_price.csv')
airbnb_room_type = pd.read_excel('data/airbnb_room_type.xlsx')
airbnb_last_review = pd.read_csv('data/airbnb_last_review.tsv', sep='\t')

print(airbnb_price.head())
print(airbnb_room_type.head())
print(airbnb_last_review.head())

   listing_id        price                nbhood_full
0        2595  225 dollars         Manhattan, Midtown
1        3831   89 dollars     Brooklyn, Clinton Hill
2        5099  200 dollars     Manhattan, Murray Hill
3        5178   79 dollars  Manhattan, Hell's Kitchen
4        5238  150 dollars       Manhattan, Chinatown
   listing_id                                description        room_type
0        2595                      Skylit Midtown Castle  Entire home/apt
1        3831            Cozy Entire Floor of Brownstone  Entire home/apt
2        5099  Large Cozy 1 BR Apartment In Midtown East  Entire home/apt
3        5178            Large Furnished Room Near B'way     private room
4        5238         Cute & Cozy Lower East Side 1 bdrm  Entire home/apt
   listing_id    host_name   last_review
0        2595     Jennifer   May 21 2019
1        3831  LisaRoxanne  July 05 2019
2        5099        Chris  June 22 2019
3        5178     Shunichi  June 24 2019
4        5238          Ben  June 09 2019

In [10]:
# Merge the three dataframes
df = pd.merge(airbnb_price, airbnb_room_type, on='listing_id')
df = pd.merge(df, airbnb_last_review, on='listing_id')
print(df.head())

   listing_id        price  ...    host_name   last_review
0        2595  225 dollars  ...     Jennifer   May 21 2019
1        3831   89 dollars  ...  LisaRoxanne  July 05 2019
2        5099  200 dollars  ...        Chris  June 22 2019
3        5178   79 dollars  ...     Shunichi  June 24 2019
4        5238  150 dollars  ...          Ben  June 09 2019

[5 rows x 7 columns]

In [11]:
# Check the datatype for each columns
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 25209 entries, 0 to 25208
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   listing_id   25209 non-null  int64
 1   price        25209 non-null  object
 2   nbhood_full  25209 non-null  object
 3   description  25199 non-null  object
 4   room_type    25209 non-null  object
 5   host_name    25201 non-null  object
 6   last_review  25209 non-null  object
dtypes: int64(1), object(6)
memory usage: 1.5+ MB

In [12]:
# Convert the last review column to date format and save it in the column 'last_review_date'
df['last_review_date'] = pd.to_datetime(df['last_review'], format='%B %d %Y')

# Find the dates of the earliest and most recent reviews
first_reviewed = df['last_review_date'].min()
last_reviewed = df['last_review_date'].max()

# Print out the results
print(f'First review date is {first_reviewed} and the most recent review date is {last_reviewed}')

First review date is 2019-01-01 00:00:00 and the most recent review date is 2019-07-09 00:00:00

In [13]:
# Check how many of the listings are private rooms. To do this, we will take a look at the 'room_type' 
# column
print(df['room_type'].value_counts())

Entire home/apt    8458
Private room       7241
entire home/apt    2665
private room       2248
ENTIRE HOME/APT    2143
PRIVATE ROOM       1867
Shared room         380
shared room         110
SHARED ROOM          97
Name: room_type, dtype: int64

In [14]:
# Next we will convert the value of the 'room_type' into the same category
df['room_type'] = df['room_type'].str.lower()

# And then we will check how many listings are private room
private_room_listing = df[df['room_type'] == 'private room'].shape[0]

print(f'There are {private_room_listing} listings are private room')

There are 11356 listings are private room

In [15]:
# Find the Average listing prive
# We see that the value of the price column is not int or float. To be able to calculate the mean of this column, we need to convert this column to float
df['price_clean'] = df['price'].str.replace(' dollars', '').astype('float')

# And then we can find the average listing price
avg_listing_price = df['price_clean'].mean()

print(f'The average lisitng price is {round(avg_listing_price,2)}')

The average lisitng price is 141.78

In [16]:
# Combine the new variables into one DataFrame
review_dates = pd.DataFrame({
    'first_reviewed': [first_reviewed], 
    'last_reviewed': [last_reviewed], 
    'nb_private_rooms': [private_room_listing], 
    'avg_price': [avg_listing_price]
})

print(review_dates)

  first_reviewed last_reviewed  nb_private_rooms   avg_price
0     2019-01-01    2019-07-09             11356  141.777936